# Generated by Django 5.2.17 on 2026-08-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='lecture_outline',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workspace',
            name='lecture_outline_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='mode',
            field=models.CharField(choices=[('socratic', 'Socratic Mode'), ('homework', 'Homework Mode'), ('lecture', 'Lecture Mode')], max_length=20),
        ),
    ]
