# Generated by Django 5.2.17 on 2026-08-14 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_workspace_lecture_outline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='live_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workspaces.material'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='live_slide_index',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('image', models.CharField(max_length=500)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='workspaces.material')),
            ],
            options={
                'ordering': ['index'],
                'constraints': [models.UniqueConstraint(fields=('material', 'index'), name='unique_slide_index_per_material')],
            },
        ),
    ]
