# Generated by Django 5.2.17 on 2026-08-15 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_studentsession_student_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RosterInvite',
        ),
    ]
