# Generated by Django 5.2.17 on 2026-08-16 04:58

from django.db import migrations, models


def mark_existing_profiles_onboarded(apps, schema_editor):
    """Existing accounts have already found their way around — don't ambush
    them with a first-run tutorial on their next login.

    The new field defaults to 'pending' so genuinely new signups get the
    tour; this flips every row that existed *before* the feature to 'done'.
    Anyone who wants it can start it from Account settings ("Replay
    tutorial"), which is also the only way to see it on an existing account.
    """
    Profile = apps.get_model('workspaces', 'Profile')
    Profile.objects.update(onboarding_status='done')


def noop_reverse(apps, schema_editor):
    # Nothing to undo: reversing the AddFields below drops both columns
    # outright, so restoring their prior values is meaningless.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_delete_rosterinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='onboarding_seen_pages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='onboarding_status',
            field=models.CharField(choices=[('pending', 'Not started'), ('active', 'In progress'), ('done', 'Finished or skipped')], default='pending', max_length=10),
        ),
        migrations.RunPython(mark_existing_profiles_onboarded, noop_reverse),
    ]
