from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('workspaces/', views.workspace_list, name='workspace_list'),
    path('new/', views.workspace_create, name='workspace_create'),
    path('settings/', views.teacher_settings, name='teacher_settings'),
    path('settings/password/', views.teacher_change_password, name='teacher_change_password'),
    path('settings/delete/', views.teacher_delete_account, name='teacher_delete_account'),
    path('<int:pk>/', views.workspace_detail, name='workspace_detail'),
    path('<int:pk>/lecture/outline/', views.generate_lecture_outline, name='generate_lecture_outline'),
    path('<int:pk>/materials/<int:material_pk>/delete/', views.material_delete, name='material_delete'),
    path('<int:pk>/materials/<int:material_pk>/slides/<int:index>/', views.slide_image, name='slide_image'),
    path('<int:pk>/present/<int:material_pk>/', views.present_material, name='present_material'),
    path('<int:pk>/present/stop/', views.stop_presenting, name='stop_presenting'),
    path('<int:pk>/present/next/', views.presenter_next, name='presenter_next'),
    path('<int:pk>/present/prev/', views.presenter_prev, name='presenter_prev'),
    path('<int:pk>/dashboard/', views.workspace_dashboard, name='workspace_dashboard'),
    path('<int:pk>/dashboard/<int:session_pk>/', views.session_transcript, name='session_transcript'),
    path('<int:pk>/dashboard/<int:session_pk>/remove/', views.student_remove, name='student_remove'),
    path('<int:pk>/dashboard/flags/<int:flag_pk>/reviewed/', views.flag_mark_reviewed, name='flag_mark_reviewed'),
    path('join/', views.student_join, name='student_join'),
    path('chat/', views.student_chat, name='student_chat'),
    path('chat/send/', views.send_message, name='send_message'),
    path('chat/live-status/', views.live_status, name='live_status'),
    path('student/login/', views.student_login, name='student_login'),
    path('student/signup/', views.student_signup, name='student_signup'),
    path('student/', views.student_home, name='student_home'),
    path('student/settings/', views.student_settings, name='student_settings'),
    path('student/settings/password/', views.student_change_password, name='student_change_password'),
    path('student/settings/delete/', views.student_delete_account, name='student_delete_account'),
    path('student/settings/<int:pk>/clear/', views.student_clear_data, name='student_clear_data'),
    path('student/<int:pk>/', views.student_workspace_transcript, name='student_workspace_transcript'),
    path('student/<int:pk>/continue/', views.student_workspace_continue, name='student_workspace_continue'),
]
